# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu1804.01"
    config.vm.synced_folder "../../data", "/data", create: true, automount: true 
    config.vm.provider "virtualbox" do |vb|
	vb.linked_clone = true
        vb.gui = true
	vb.memory = 2048
	vb.cpus = 2
        vb.customize ['modifyvm', :id, '--clipboard','bidirectional']
        vb.customize ['modifyvm', :id, '--draganddrop','bidirectional']   
    end
    config.vm.provision "shell",  path: "base.sh", reboot: true
 
    config.vm.define "base", primary: true do |base|
	base.vm.provider "virtualbox" do |vb|
	    vb.name = "base"		
	end
	base.vm.hostname = "base"
	base.vm.provision "shell", inline: "echo BaseBox"
	base.vm.network "forwarded_port", guest: 22, host: 2251
    end

    config.vm.define "sleuthkit_49" do |sleuthkit_49|
	sleuthkit_49.vm.provider "virtualbox" do |vb|
	    vb.name = "sleuthkit-49"		
	end
    	sleuthkit_49.vm.hostname = "sleuthkit-49"
	sleuthkit_49.vm.provision "shell", inline: "echo Sleuthkit 4.9"
        sleuthkit_49.vm.provision "shell",  path: "sleuthkit-49.sh", reboot: true   
 	sleuthkit_49.vm.network "forwarded_port", guest: 22, host: 2252
    end

    config.vm.define "sleuthkit_fkiecad" do |sleuthkit_fkiecad|
	sleuthkit_fkiecad.vm.provider "virtualbox" do |vb|
	    vb.name = "sleuthkit-fkiecad"		
	end
	sleuthkit_fkiecad.vm.hostname = "sleuthkit-fkiecad"
	sleuthkit_fkiecad.vm.provision "shell", inline: "echo Sleuthkit FKIE-CAD"
        sleuthkit_fkiecad.vm.provision "shell",  path: "sleuthkit-fkiecad.sh", reboot: true    
	sleuthkit_fkiecad.vm.network "forwarded_port", guest: 22, host: 2253
    end

    config.vm.define "sleuthkit_faui" do |sleuthkit_faui|
	sleuthkit_faui.vm.provider "virtualbox" do |vb|
	    vb.name = "sleuthkit-faui"		
	end
	sleuthkit_faui.vm.hostname = "sleuthkit-faui"
	sleuthkit_faui.vm.provision "shell", inline: "echo Sleuthkit faui"
        sleuthkit_faui.vm.provision "shell",  path: "sleuthkit-faui.sh", reboot: true    
	sleuthkit_faui.vm.network "forwarded_port", guest: 22, host: 2254
    end

    config.vm.define "generator_lnx", primary: true do |generator_lnx|
	generator_lnx.vm.provider "virtualbox" do |vb|
	    vb.name = "generator-lnx"		
	end
	generator_lnx.vm.hostname = "generator-lnx"
	generator_lnx.vm.provision "shell", inline: "echo Generator"
	generator_lnx.vm.provision "shell", path: "generator.sh"
	generator_lnx.vm.network "forwarded_port", guest: 22, host: 2255
    end

end

