# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "windowssrv2019core"
    config.vm.guest = :windows
    config.vm.communicator = "winrm"
    config.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
        vb.gui = true
        vb.memory = 8192
        vb.cpus = 4
        vb.customize ['modifyvm', :id, '--clipboard','bidirectional']
        vb.customize ['modifyvm', :id, '--draganddrop','bidirectional']
	vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]    
    end
    config.vm.synced_folder "../../data", "c:\\data", create: true, automount: true

    config.vm.define "generator_win", primary: true do |generator_win|
        generator_win.vm.provider "virtualbox" do |vb|
            vb.name = "generator-win"
        end
        generator_win.vm.hostname = "generator-win"
        generator_win.vm.provision "shell", path: "generator-win.ps1", reboot: true
        generator_win.vm.provision "shell", inline: "echo generator_win"
	generator_win.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true  
    end
end
